"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { useToast } from "@/components/ui/toast";
import { formatDate, formatDateTime, daysSince, levelLabel, statusLabel } from "@/lib/utils";
import { StudentForm } from "../student-form";

type FullStudent = {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  birthdate: Date | null;
  city: string | null;
  goal: string | null;
  level: string;
  daysPerWeek: number;
  sessionDuration: number;
  restrictions: string | null;
  equipment: string | null;
  notes: string | null;
  status: string;
  mfitId: string | null;
  lastContactAt: Date | null;
  createdAt: Date;
  photos: { id: string; url: string; angle: string | null; takenAt: Date }[];
  workouts: {
    id: string;
    title: string;
    status: string;
    createdAt: Date;
    mfitSyncedAt: Date | null;
    sessions: {
      id: string;
      name: string;
      order: number;
      exercises: { id: string; name: string; sets: number; reps: string; rest: number; notes: string | null; order: number }[];
    }[];
  }[];
  followUps: {
    id: string;
    message: string;
    channel: string;
    status: string;
    autoGenerated: boolean;
    sentAt: Date;
  }[];
};

export function StudentProfile({ student }: { student: FullStudent }) {
  const router = useRouter();
  const { toast } = useToast();
  const [tab, setTab] = useState<"dados" | "fotos" | "treinos" | "acompanhamento">("dados");
  const [editing, setEditing] = useState(false);
  const [deleteModal, setDeleteModal] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [uploadingPhoto, setUploadingPhoto] = useState(false);
  const [generateModal, setGenerateModal] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [followModal, setFollowModal] = useState(false);
  const [followMessage, setFollowMessage] = useState("");
  const [followChannel, setFollowChannel] = useState("email");
  const [sendingFollow, setSendingFollow] = useState(false);
  const [generatingMsg, setGeneratingMsg] = useState(false);

  async function handleDelete() {
    setDeleting(true);
    const res = await fetch(`/api/students/${student.id}`, { method: "DELETE" });
    if (res.ok) {
      toast("Aluno excluído");
      router.push("/alunos");
    } else {
      toast("Erro ao excluir", "error");
      setDeleting(false);
    }
  }

  async function handlePhotoUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploadingPhoto(true);
    const form = new FormData();
    form.append("file", file);
    form.append("angle", "frente");
    const res = await fetch(`/api/students/${student.id}/photos`, { method: "POST", body: form });
    if (res.ok) {
      toast("Foto enviada!");
      router.refresh();
    } else {
      toast("Erro ao enviar foto", "error");
    }
    setUploadingPhoto(false);
  }

  async function handleGenerateWorkout() {
    setGenerating(true);
    const res = await fetch(`/api/students/${student.id}/workouts`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ generate: true }),
    });
    if (res.ok) {
      const workout = await res.json();
      toast("Treino gerado com IA!");
      setGenerateModal(false);
      router.push(`/treinos/${workout.id}`);
    } else {
      toast("Erro ao gerar treino", "error");
    }
    setGenerating(false);
  }

  async function handleGenerateMessage() {
    setGeneratingMsg(true);
    const res = await fetch("/api/followups/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ studentId: student.id }),
    });
    if (res.ok) {
      const data = await res.json();
      setFollowMessage(data.message);
    } else {
      toast("Erro ao gerar mensagem", "error");
    }
    setGeneratingMsg(false);
  }

  async function handleSendFollow() {
    if (!followMessage.trim()) return;
    setSendingFollow(true);
    const res = await fetch("/api/followups/send", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ studentId: student.id, message: followMessage, channel: followChannel }),
    });
    if (res.ok) {
      toast("Mensagem enviada!");
      setFollowModal(false);
      setFollowMessage("");
      router.refresh();
    } else {
      toast("Erro ao enviar mensagem", "error");
    }
    setSendingFollow(false);
  }

  const tabs = [
    { key: "dados", label: "Dados", icon: "person" },
    { key: "fotos", label: "Fotos", icon: "photo_camera" },
    { key: "treinos", label: "Treinos", icon: "fitness_center" },
    { key: "acompanhamento", label: "Acompanhamento", icon: "chat" },
  ] as const;

  if (editing) {
    return (
      <div>
        <div className="mb-8 flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={() => setEditing(false)}>
            <span className="material-symbols-outlined text-[18px]">arrow_back</span>
          </Button>
          <h1 className="text-2xl font-bold text-on-surface">Editar {student.name}</h1>
        </div>
        <StudentForm
          studentId={student.id}
          defaultValues={{
            name: student.name,
            email: student.email,
            phone: student.phone ?? "",
            birthdate: student.birthdate ? new Date(student.birthdate).toISOString().split("T")[0] : "",
            city: student.city ?? "",
            goal: student.goal ?? "",
            level: student.level,
            daysPerWeek: String(student.daysPerWeek),
            sessionDuration: String(student.sessionDuration),
            restrictions: student.restrictions ?? "",
            equipment: student.equipment ?? "",
            notes: student.notes ?? "",
            status: student.status,
            mfitId: student.mfitId ?? "",
          }}
        />
      </div>
    );
  }

  return (
    <div>
      <div className="mb-6 flex items-start justify-between gap-4">
        <div className="flex items-center gap-3">
          <Link href="/alunos">
            <Button variant="ghost" size="icon">
              <span className="material-symbols-outlined text-[18px]">arrow_back</span>
            </Button>
          </Link>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-2xl font-bold text-on-surface">{student.name}</h1>
              <Badge
                variant={student.status === "ativo" ? "success" : student.status === "pausado" ? "warning" : "secondary"}
              >
                {statusLabel(student.status)}
              </Badge>
            </div>
            <p className="text-sm text-on-surface-variant">{student.email}</p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={() => setEditing(true)}>
            <span className="material-symbols-outlined text-[18px]">edit</span>
            Editar
          </Button>
          <Button variant="destructive" size="sm" onClick={() => setDeleteModal(true)}>
            <span className="material-symbols-outlined text-[18px]">delete</span>
          </Button>
        </div>
      </div>

      {/* Tabs */}
      <div className="mb-6 flex gap-1 border-b border-outline-variant">
        {tabs.map(({ key, label, icon }) => (
          <button
            key={key}
            onClick={() => setTab(key)}
            className={`flex items-center gap-2 px-4 py-2.5 text-sm font-medium transition-colors border-b-2 -mb-px ${
              tab === key
                ? "border-primary text-primary"
                : "border-transparent text-on-surface-variant hover:text-on-surface"
            }`}
          >
            <span className="material-symbols-outlined text-[18px]">{icon}</span>
            {label}
          </button>
        ))}
      </div>

      {/* Dados */}
      {tab === "dados" && (
        <div className="grid gap-4 sm:grid-cols-2">
          <Card>
            <CardHeader><CardTitle>Informações pessoais</CardTitle></CardHeader>
            <CardContent className="space-y-3 text-sm">
              {[
                ["Telefone", student.phone],
                ["Nascimento", student.birthdate ? formatDate(student.birthdate) : null],
                ["Cidade", student.city],
                ["ID MFIT", student.mfitId],
                ["Cadastro", formatDate(student.createdAt)],
                ["Último contato", student.lastContactAt ? formatDate(student.lastContactAt) : "Nunca"],
              ].map(([label, value]) => (
                <div key={label} className="flex justify-between">
                  <span className="text-on-surface-variant">{label}</span>
                  <span className="text-on-surface">{value ?? "—"}</span>
                </div>
              ))}
            </CardContent>
          </Card>
          <Card>
            <CardHeader><CardTitle>Perfil de treino</CardTitle></CardHeader>
            <CardContent className="space-y-3 text-sm">
              {[
                ["Objetivo", student.goal],
                ["Nível", levelLabel(student.level)],
                ["Dias/semana", `${student.daysPerWeek} dias`],
                ["Duração", `${student.sessionDuration} min`],
              ].map(([label, value]) => (
                <div key={label} className="flex justify-between">
                  <span className="text-on-surface-variant">{label}</span>
                  <span className="text-on-surface">{value ?? "—"}</span>
                </div>
              ))}
            </CardContent>
          </Card>
          {student.restrictions && (
            <Card>
              <CardHeader><CardTitle>Restrições</CardTitle></CardHeader>
              <CardContent><p className="text-sm text-on-surface">{student.restrictions}</p></CardContent>
            </Card>
          )}
          {student.equipment && (
            <Card>
              <CardHeader><CardTitle>Equipamentos</CardTitle></CardHeader>
              <CardContent><p className="text-sm text-on-surface">{student.equipment}</p></CardContent>
            </Card>
          )}
          {student.notes && (
            <Card className="sm:col-span-2">
              <CardHeader><CardTitle>Observações</CardTitle></CardHeader>
              <CardContent><p className="text-sm text-on-surface">{student.notes}</p></CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Fotos */}
      {tab === "fotos" && (
        <div>
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-lg font-semibold text-on-surface">Fotos de avaliação</h2>
            <label>
              <Button variant="outline" size="sm" disabled={uploadingPhoto} onClick={() => {}}>
                {uploadingPhoto ? <span className="material-symbols-outlined text-[18px] animate-spin">refresh</span> : <span className="material-symbols-outlined text-[18px]">upload</span>}
                Enviar foto
              </Button>
              <input type="file" accept="image/*" className="hidden" onChange={handlePhotoUpload} />
            </label>
          </div>
          {student.photos.length === 0 ? (
            <div className="rounded-xl border border-dashed border-outline-variant p-12 text-center">
              <span className="material-symbols-outlined text-[32px] text-on-surface-variant mx-auto mb-3 block">photo_camera</span>
              <p className="text-sm text-on-surface-variant">Nenhuma foto enviada ainda</p>
            </div>
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
              {student.photos.map((photo) => (
                <div key={photo.id} className="rounded-xl overflow-hidden border border-outline-variant bg-surface-container">
                  <img src={photo.url} alt={photo.angle ?? "Foto"} className="w-full aspect-[3/4] object-cover" />
                  <div className="px-2 py-1.5">
                    <p className="text-xs text-on-surface-variant">{photo.angle ?? "Foto"}</p>
                    <p className="text-xs text-on-surface-variant">{formatDate(photo.takenAt)}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Treinos */}
      {tab === "treinos" && (
        <div>
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-lg font-semibold text-on-surface">Treinos</h2>
            <Button size="sm" onClick={() => setGenerateModal(true)}>
              <span className="material-symbols-outlined text-[18px]">auto_fix_high</span>
              Gerar com IA
            </Button>
          </div>
          {student.workouts.length === 0 ? (
            <div className="rounded-xl border border-dashed border-outline-variant p-12 text-center">
              <span className="material-symbols-outlined text-[32px] text-on-surface-variant mx-auto mb-3 block">fitness_center</span>
              <p className="text-sm text-on-surface-variant">Nenhum treino gerado ainda</p>
              <Button size="sm" className="mt-4" onClick={() => setGenerateModal(true)}>
                <span className="material-symbols-outlined text-[18px]">auto_fix_high</span>
                Gerar primeiro treino
              </Button>
            </div>
          ) : (
            <div className="space-y-3">
              {student.workouts.map((workout) => (
                <Card key={workout.id} className="flex items-center justify-between">
                  <div>
                    <p className="font-medium text-on-surface">{workout.title}</p>
                    <p className="text-xs text-on-surface-variant mt-0.5">{formatDate(workout.createdAt)} · {workout.sessions.length} sessões</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge
                      variant={
                        workout.status === "aprovado" ? "success"
                        : workout.status === "enviado_mfit" ? "secondary"
                        : "outline"
                      }
                    >
                      {workout.status === "rascunho" ? "Rascunho" : workout.status === "aprovado" ? "Aprovado" : "No MFIT"}
                    </Badge>
                    <Link href={`/treinos/${workout.id}`}>
                      <Button variant="ghost" size="sm">
                        <span className="material-symbols-outlined text-[18px]">open_in_new</span>
                        Ver
                      </Button>
                    </Link>
                  </div>
                </Card>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Acompanhamento */}
      {tab === "acompanhamento" && (
        <div>
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-lg font-semibold text-on-surface">Histórico de acompanhamento</h2>
            <Button size="sm" onClick={() => setFollowModal(true)}>
              <span className="material-symbols-outlined text-[18px]">send</span>
              Enviar mensagem
            </Button>
          </div>
          {student.followUps.length === 0 ? (
            <div className="rounded-xl border border-dashed border-outline-variant p-12 text-center">
              <span className="material-symbols-outlined text-[32px] text-on-surface-variant mx-auto mb-3 block">chat</span>
              <p className="text-sm text-on-surface-variant">Nenhuma mensagem enviada ainda</p>
            </div>
          ) : (
            <div className="space-y-3">
              {student.followUps.map((f) => (
                <Card key={f.id}>
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1">
                      <p className="text-sm text-on-surface whitespace-pre-wrap">{f.message}</p>
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-xs text-on-surface-variant">{formatDateTime(f.sentAt)}</p>
                      <Badge variant="secondary" className="mt-1">{f.channel}</Badge>
                      {f.autoGenerated && <Badge variant="outline" className="mt-1 ml-1">IA</Badge>}
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Delete Modal */}
      <Modal open={deleteModal} onClose={() => setDeleteModal(false)} title="Excluir aluno">
        <p className="text-sm text-on-surface-variant mb-6">
          Tem certeza que deseja excluir <strong className="text-on-surface">{student.name}</strong>? Esta ação não pode ser desfeita.
        </p>
        <div className="flex gap-3 justify-end">
          <Button variant="outline" onClick={() => setDeleteModal(false)}>Cancelar</Button>
          <Button variant="destructive" onClick={handleDelete} disabled={deleting}>
            {deleting ? <span className="material-symbols-outlined text-[18px] animate-spin">refresh</span> : <span className="material-symbols-outlined text-[18px]">delete</span>}
            Excluir
          </Button>
        </div>
      </Modal>

      {/* Generate Workout Modal */}
      <Modal open={generateModal} onClose={() => setGenerateModal(false)} title="Gerar treino com IA">
        <p className="text-sm text-on-surface-variant mb-6">
          A IA vai analisar o perfil de <strong className="text-on-surface">{student.name}</strong> e gerar um treino personalizado.
        </p>
        <div className="flex gap-3 justify-end">
          <Button variant="outline" onClick={() => setGenerateModal(false)}>Cancelar</Button>
          <Button onClick={handleGenerateWorkout} disabled={generating}>
            {generating ? <span className="material-symbols-outlined text-[18px] animate-spin">refresh</span> : <span className="material-symbols-outlined text-[18px]">auto_fix_high</span>}
            {generating ? "Gerando..." : "Gerar treino"}
          </Button>
        </div>
      </Modal>

      {/* Follow-up Modal */}
      <Modal open={followModal} onClose={() => setFollowModal(false)} title="Enviar mensagem" className="max-w-xl">
        <div className="space-y-4">
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleGenerateMessage} disabled={generatingMsg}>
              {generatingMsg ? <span className="material-symbols-outlined text-[18px] animate-spin">refresh</span> : <span className="material-symbols-outlined text-[18px]">auto_fix_high</span>}
              Gerar com IA
            </Button>
          </div>
          <Textarea
            rows={6}
            placeholder="Escreva a mensagem ou gere com IA..."
            value={followMessage}
            onChange={(e) => setFollowMessage(e.target.value)}
          />
          <Select value={followChannel} onChange={(e) => setFollowChannel(e.target.value)}>
            <option value="email">E-mail</option>
            <option value="whatsapp">WhatsApp</option>
          </Select>
          <div className="flex gap-3 justify-end">
            <Button variant="outline" onClick={() => setFollowModal(false)}>Cancelar</Button>
            <Button onClick={handleSendFollow} disabled={sendingFollow || !followMessage.trim()}>
              {sendingFollow ? <span className="material-symbols-outlined text-[18px] animate-spin">refresh</span> : <span className="material-symbols-outlined text-[18px]">send</span>}
              Enviar
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
