import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import nodemailer from "nodemailer";

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { studentId, message, channel, autoGenerated = false } = await req.json();

  const [studentResult, settingsResult] = await Promise.all([
    supabase.from("Student").select("*").eq("id", studentId).single(),
    supabase.from("Settings").select("*").limit(1).maybeSingle(),
  ]);

  if (!studentResult.data) return NextResponse.json({ error: "Student not found" }, { status: 404 });

  const student = studentResult.data as any;
  const settings = settingsResult.data as any;

  let sendStatus = "enviado";

  try {
    if (channel === "email" && settings?.smtpHost && student.email) {
      const transporter = nodemailer.createTransport({
        host: settings.smtpHost,
        port: settings.smtpPort ?? 587,
        secure: (settings.smtpPort ?? 587) === 465,
        auth: { user: settings.smtpUser ?? "", pass: settings.smtpPass ?? "" },
      });

      await transporter.sendMail({
        from: settings.smtpFrom ?? settings.smtpUser ?? undefined,
        to: student.email,
        subject: "Acompanhamento do seu personal trainer",
        text: message,
      });
    } else if (channel === "whatsapp" && settings?.zapiToken && settings?.zapiInstance) {
      const phone = student.phone ?? settings.zapiPhone;
      if (phone) {
        await fetch(
          `https://api.z-api.io/instances/${settings.zapiInstance}/token/${settings.zapiToken}/send-text`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ phone, message }),
          }
        );
      }
    }
  } catch (e) {
    console.error("Send error:", e);
    sendStatus = "falhou";
  }

  const { data: followUp } = await supabase
    .from("FollowUp")
    .insert({
      studentId,
      message,
      channel,
      status: sendStatus,
      autoGenerated,
    })
    .select()
    .single();

  await supabase
    .from("Student")
    .update({ lastContactAt: new Date().toISOString() })
    .eq("id", studentId);

  return NextResponse.json(followUp, { status: 201 });
}
