import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import nodemailer from "nodemailer";

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { studentId, message, channel, autoGenerated = false } = await req.json();

  const [student, settings] = await Promise.all([
    prisma.student.findUnique({ where: { id: studentId } }),
    prisma.settings.findFirst(),
  ]);

  if (!student) return NextResponse.json({ error: "Student not found" }, { status: 404 });

  let sendStatus = "enviado";

  try {
    if (channel === "email" && settings?.smtpHost && student.email) {
      const transporter = nodemailer.createTransport({
        host: settings.smtpHost,
        port: settings.smtpPort ?? 587,
        secure: (settings.smtpPort ?? 587) === 465,
        auth: { user: settings.smtpUser ?? "", pass: settings.smtpPass ?? "" },
      });

      await transporter.sendMail({
        from: settings.smtpFrom ?? settings.smtpUser ?? undefined,
        to: student.email,
        subject: "Acompanhamento do seu personal trainer",
        text: message,
      });
    } else if (channel === "whatsapp" && settings?.zapiToken && settings?.zapiInstance) {
      const phone = student.phone ?? settings.zapiPhone;
      if (phone) {
        await fetch(
          `https://api.z-api.io/instances/${settings.zapiInstance}/token/${settings.zapiToken}/send-text`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ phone, message }),
          }
        );
      }
    }
  } catch (e) {
    console.error("Send error:", e);
    sendStatus = "falhou";
  }

  const followUp = await prisma.followUp.create({
    data: {
      studentId,
      message,
      channel,
      status: sendStatus,
      autoGenerated,
    },
  });

  await prisma.student.update({
    where: { id: studentId },
    data: { lastContactAt: new Date() },
  });

  return NextResponse.json(followUp, { status: 201 });
}
