import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { aiComplete } from "@/lib/ai";
import nodemailer from "nodemailer";

export async function GET(req: NextRequest) {
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const settings = await prisma.settings.findFirst();
  const cutoff = new Date(Date.now() - 15 * 24 * 60 * 60 * 1000);

  const students = await prisma.student.findMany({
    where: {
      status: "ativo",
      OR: [
        { lastContactAt: { lt: cutoff } },
        { lastContactAt: null, createdAt: { lt: cutoff } },
      ],
    },
    include: {
      workouts: { orderBy: { createdAt: "desc" }, take: 1 },
    },
  });

  const results: string[] = [];

  for (const student of students) {
    try {
      const template =
        settings?.followUpTemplate ??
        "Olá {nome}! Tudo bem? Passando para ver como está indo o {treino_atual}. Qualquer dúvida pode me chamar!";

      const lastWorkout = student.workouts[0]?.title ?? "treino atual";
      const prompt = `Você é assistente de um personal trainer.
Escreva uma mensagem de acompanhamento personalizada para o aluno abaixo.
A mensagem deve ser natural, motivadora, e parecer escrita pelo personal.
Máximo de 3 parágrafos. Sem formalidade excessiva.

ALUNO: ${student.name}
OBJETIVO: ${student.goal ?? "Não especificado"}
TREINO ATUAL: ${lastWorkout}
Template base: ${template}

Retorne APENAS o texto da mensagem.`;

      const message = await aiComplete(prompt, 500);

      if (settings?.autoFollowUp && message) {
        let sendStatus = "enviado";
        let channel = "email";

        if (settings.smtpHost && student.email) {
          try {
            const transporter = nodemailer.createTransport({
              host: settings.smtpHost,
              port: settings.smtpPort ?? 587,
              secure: (settings.smtpPort ?? 587) === 465,
              auth: { user: settings.smtpUser ?? "", pass: settings.smtpPass ?? "" },
            });
            await transporter.sendMail({
              from: settings.smtpFrom ?? settings.smtpUser ?? undefined,
              to: student.email,
              subject: "Acompanhamento do seu personal trainer",
              text: message,
            });
          } catch {
            sendStatus = "falhou";
          }
        } else if (settings.zapiToken && settings.zapiInstance && student.phone) {
          channel = "whatsapp";
          try {
            await fetch(
              `https://api.z-api.io/instances/${settings.zapiInstance}/token/${settings.zapiToken}/send-text`,
              {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ phone: student.phone, message }),
              }
            );
          } catch {
            sendStatus = "falhou";
          }
        }

        await prisma.followUp.create({
          data: { studentId: student.id, message, channel, status: sendStatus, autoGenerated: true },
        });

        if (sendStatus === "enviado") {
          await prisma.student.update({
            where: { id: student.id },
            data: { lastContactAt: new Date() },
          });
        }

        results.push(`${student.name}: ${sendStatus}`);
      } else {
        await prisma.followUp.create({
          data: { studentId: student.id, message, channel: "email", status: "pendente", autoGenerated: true },
        });
        results.push(`${student.name}: pendente`);
      }
    } catch (e) {
      console.error(`Error processing ${student.name}:`, e);
      results.push(`${student.name}: erro`);
    }
  }

  return NextResponse.json({ processed: students.length, results });
}
