import { NextRequest, NextResponse } from "next/server";
import { timingSafeEqual } from "crypto";
import { supabase } from "@/lib/supabase";
import { aiComplete } from "@/lib/ai";
import nodemailer from "nodemailer";

export async function GET(req: NextRequest) {
  const authHeader = req.headers.get("authorization") ?? "";
  const expected = `Bearer ${process.env.CRON_SECRET ?? ""}`;
  const authorized =
    authHeader.length === expected.length &&
    timingSafeEqual(Buffer.from(authHeader), Buffer.from(expected));
  if (!authorized) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: settings } = await supabase.from("Settings").select("*").limit(1).maybeSingle();
  const cutoff = new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString();

  const { data: studentsRaw } = await supabase
    .from("Student")
    .select("*, Workout(*)")
    .eq("status", "ativo")
    .or(`lastContactAt.lt.${cutoff},and(lastContactAt.is.null,createdAt.lt.${cutoff})`);

  const students = (studentsRaw ?? []).map((s: any) => ({
    ...s,
    workouts: s.Workout
      ? [...s.Workout].sort(
          (a: any, b: any) =>
            new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        ).slice(0, 1)
      : [],
  }));

  const template =
    settings?.followUpTemplate ??
    "Olá {nome}! Tudo bem? Passando para ver como está indo o {treino_atual}. Qualquer dúvida pode me chamar!";

  const resultEntries = await Promise.allSettled(
    students.map(async (student) => {
      const lastWorkout = student.workouts[0]?.title ?? "treino atual";
      const prompt = `Você é assistente de um personal trainer.
Escreva uma mensagem de acompanhamento personalizada para o aluno abaixo.
A mensagem deve ser natural, motivadora, e parecer escrita pelo personal.
Máximo de 3 parágrafos. Sem formalidade excessiva.

ALUNO: ${student.name}
OBJETIVO: ${student.goal ?? "Não especificado"}
TREINO ATUAL: ${lastWorkout}
Template base: ${template}

Retorne APENAS o texto da mensagem.`;

      const message = await aiComplete(prompt, 500);

      if (settings?.autoFollowUp && message) {
        let sendStatus = "enviado";
        let channel = "email";

        if (settings.smtpHost && student.email) {
          try {
            const transporter = nodemailer.createTransport({
              host: settings.smtpHost,
              port: settings.smtpPort ?? 587,
              secure: (settings.smtpPort ?? 587) === 465,
              auth: { user: settings.smtpUser ?? "", pass: settings.smtpPass ?? "" },
            });
            await transporter.sendMail({
              from: settings.smtpFrom ?? settings.smtpUser ?? undefined,
              to: student.email,
              subject: "Acompanhamento do seu personal trainer",
              text: message,
            });
          } catch {
            sendStatus = "falhou";
          }
        } else if (
          settings.zapiToken?.trim() &&
          settings.zapiInstance?.trim() &&
          settings.zapiClientToken?.trim() &&
          student.phone
        ) {
          channel = "whatsapp";
          try {
            const phone = String(student.phone).replace(/\D/g, "");
            const zapiRes = await fetch(
              `https://api.z-api.io/instances/${settings.zapiInstance.trim()}/token/${settings.zapiToken.trim()}/send-text`,
              {
                method: "POST",
                headers: { "Content-Type": "application/json", "Client-Token": settings.zapiClientToken.trim() },
                body: JSON.stringify({ phone, message }),
              }
            );
            if (!zapiRes.ok) sendStatus = "falhou";
          } catch {
            sendStatus = "falhou";
          }
        }

        await supabase.from("FollowUp").insert({
          id: crypto.randomUUID(),
          studentId: student.id,
          message,
          channel,
          status: sendStatus,
          autoGenerated: true,
        });

        if (sendStatus === "enviado") {
          await supabase
            .from("Student")
            .update({ lastContactAt: new Date().toISOString() })
            .eq("id", student.id);
        }

        return `${student.name}: ${sendStatus}`;
      } else {
        await supabase.from("FollowUp").insert({
          id: crypto.randomUUID(),
          studentId: student.id,
          message,
          channel: "email",
          status: "pendente",
          autoGenerated: true,
        });
        return `${student.name}: pendente`;
      }
    })
  );

  const results = resultEntries.map((r, i) =>
    r.status === "fulfilled" ? r.value : `${students[i].name}: erro`
  );

  return NextResponse.json({ processed: students.length, results });
}
